# Kubernetes Aliases
alias k='kubectl'
alias kgp='kubectl get pods'
alias kgs='kubectl get svc'
alias kgn='kubectl get nodes'
alias kga='kubectl get all'
alias kctx='kubectl config use-context'
alias kns='kubectl config set-context --current --namespace'
alias klogs='kubectl logs'
alias klogsf='kubectl logs -f'
alias kexec='kubectl exec -it'
alias kdesc='kubectl describe'
alias krm='kubectl delete'
alias kaf='kubectl apply -f'
alias kdf='kubectl delete -f'
alias kedit='kubectl edit'
