# Docker Aliases
alias d='docker'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dstart='docker start'
alias dstop='docker stop'
alias drm='docker rm'
alias drmi='docker rmi'
alias dimg='docker images'
alias dbash='docker exec -it'
alias dlogs='docker logs'
alias dlogsf='docker logs -f'
alias dnet='docker network ls'
alias dvol='docker volume ls'
alias dprune='docker system prune -af'
alias dclean='docker rm $(docker ps -aq) && docker rmi $(docker images -q)'
